version: "3.7"

services:
  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/www:/www:ro"
      - "./nginx/conf.d:/etc/nginx/conf.d:ro"
      - "/etc/letsencrypt/live/${FULL_DOMAIN_NAME}:/etc/letsencrypt/live/${FULL_DOMAIN_NAME}:ro"
      - "/etc/letsencrypt/archive/${FULL_DOMAIN_NAME}:/etc/letsencrypt/archive/${FULL_DOMAIN_NAME}:ro"

  jenkins:
    image: jenkins/jenkins:lts
    restart: unless-stopped
    volumes:
      - "jenkins-ci:/var/jenkins_home"
#    ports:
#      - "8080:8080"
#      - "50000:50000"

volumes:
  jenkins-ci:
